language: go

install:
    - go get -v github.com/gohugoio/hugo

script:
    - mkdir themes
    - git clone https://github.com/KuTuGu/hugo-theme-terminal themes/terminal
    - hugo --minify
    
deploy:
    provider: pages
    keep-history: true
    skip-cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    on:
        branch: master