languageCode = "en-US"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "colorful"
  showMenuItems = 10
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "KuTuGu的博客"
    keywords = "前端 博客"
    menuMore = "显示更多"
    readMore = "阅读文章"
    readOtherPosts = "阅读其它文章"

    [languages.en.params.logo]
      logoText = "主页"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/KuTuGu"
      [[languages.en.menu.main]]
        identifier = "resume"
        name = "简历"
        url = "https://kutugu.github.io/resume"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
