# 先将打包出来的js、css文件路径转为绝对路径
# "assets/style.css" => "/assets/style.css"
baseurl = "/"
# 在根据当前文件路径，将绝对路径转为相对路径
# 从而使博客放置在子目录路径，也可以正确读取资源
# "/assets/style.css" => "../../assets/style.css"
relativeURLs = true
languageCode = "en-US"
theme = "terminal"

[params]
  contentTypeName = "post"
  showMenuItems = 10
  fullWidthTheme = false
  centerTheme = true
  showColorful=true
  favicon="img/favicon/icon.png"

[languages]
  [languages.en]
    title = "KuTuGu's Blog"
    menuMore = "显示更多"
    readMore = "阅读文章"
    readOtherPosts = "阅读其它文章"

    [languages.en.params.logo]
      logoText = "Main"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/KuTuGu"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/kutugu1"
      [[languages.en.menu.main]]
        identifier = "resume_zh"
        name = "Resume_zh"
        url = "/resume_zh"
      [[languages.en.menu.main]]
        identifier = "resume_en"
        name = "Resume_en"
        url = "/resume_en"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
